//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Settings/Input/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""_Game"",
            ""id"": ""0ee24a4d-0aaa-4626-a2b5-7b0111ca7aa6"",
            ""actions"": [
                {
                    ""name"": ""Quitgame"",
                    ""type"": ""Button"",
                    ""id"": ""9f743778-0e19-44e5-9e52-673bb2623329"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RestartLevel"",
                    ""type"": ""Button"",
                    ""id"": ""7493fc91-5af9-4fde-8b7c-289c33e6a217"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TogglePostProcessing"",
                    ""type"": ""Button"",
                    ""id"": ""6563394a-763b-45c5-a05f-cfa94a4c74c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MusicMute"",
                    ""type"": ""Button"",
                    ""id"": ""31472298-08fc-4635-b431-9af0de2d324f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleUI"",
                    ""type"": ""Button"",
                    ""id"": ""c05c5df0-d5fd-4147-a42c-64e9c50c7c70"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Screenshot"",
                    ""type"": ""Button"",
                    ""id"": ""07c3089c-2e3d-474a-96fb-07418e7ed38e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""89451404-8c99-4d2d-859c-c404255992b0"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Quitgame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2964e1ed-e871-42c8-ba54-dd1c31f8e349"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Quitgame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1de9da25-4828-4995-9b19-9d208ac0e21a"",
                    ""path"": ""<Keyboard>/f9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""RestartLevel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6f144c1-ff0e-4f4e-9db7-d1f7b31c6f2b"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RestartLevel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d8ecd9b-ef05-4e1c-8ddd-5afdf29de556"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""TogglePostProcessing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96d41486-d879-411f-af39-4b6525e4a02f"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""TogglePostProcessing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f4cebbc-21bc-4c2a-b277-e06ccf1fe1be"",
                    ""path"": ""<Keyboard>/f12"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Screenshot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""53553359-31e8-4070-84ff-4caf6eacf892"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Screenshot"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""f0bdf77a-33bf-4ead-b8d8-906ab94982aa"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Screenshot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""a3448745-246e-477f-a71e-0c6cd0036cd5"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Screenshot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e1318847-3ec7-4b59-b620-4d4a2fa0cc4e"",
                    ""path"": ""<Keyboard>/f2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""MusicMute"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd58af00-813e-4fd6-b113-81478373787c"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""MusicMute"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ea6d185-e22c-4c23-bc96-90e03462075b"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ToggleUI"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1297abf0-0e0d-4c1b-9bc8-a0e2fdc9e565"",
                    ""path"": ""<Keyboard>/f4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""ToggleUI"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""_Camera"",
            ""id"": ""8da3decc-e41f-428a-bb81-46d9f2e3e7a5"",
            ""actions"": [
                {
                    ""name"": ""Horizontal"",
                    ""type"": ""Value"",
                    ""id"": ""05491381-ed47-4f6c-9509-0053d55fb80a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Vertical"",
                    ""type"": ""Value"",
                    ""id"": ""1f0c7476-5694-4e59-b893-2e059dba706e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Q-E"",
                    ""id"": ""ce42f279-8466-4ae5-bfe3-00f7f2e11b6d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Horizontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c9a41c98-a78b-452e-9548-c0f666343540"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""00681802-cb0b-4838-8a35-b80782965d7c"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right stick horizontal"",
                    ""id"": ""f75986be-fd72-405c-9349-dfad66f8d6e5"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125,max=1)"",
                    ""groups"": """",
                    ""action"": ""Horizontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""1d88c67f-76ed-4919-ac62-769fc66b557d"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""b28457df-7955-4175-9a6f-210e97b86086"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""F-R"",
                    ""id"": ""23512ab4-1ac7-4791-a9ca-85993aea5682"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Vertical"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""f9b9c2bf-a22d-45b4-876d-ada15912a2da"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""83dfb1b5-0878-4bd4-a40d-0ac0038dde20"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right stick vertical"",
                    ""id"": ""909046ac-481e-4d7b-8d63-d710c8e18390"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.75,max=1)"",
                    ""groups"": """",
                    ""action"": ""Vertical"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""dc9ed118-a6e8-4dc1-885f-7fa583cd200e"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""70d7eeea-053e-4e2f-98d8-5469dd89c83f"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""_Player"",
            ""id"": ""952d2b8c-cbe6-4b6c-9a74-36c7e315ac9e"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5d8c2c57-0fff-4c5b-bc8a-61e41545ebcc"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""PassThrough"",
                    ""id"": ""59c8af58-7028-4e8e-a09b-bd1fa209bd15"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability01_Tap"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0708dccb-8db5-482a-abd2-7dcea75bfafc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability02_Tap"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7259e08e-72f4-495b-b997-879b99d6234f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability03_Tap"",
                    ""type"": ""PassThrough"",
                    ""id"": ""38aa15fe-fb8b-49c4-81e9-3f356c286d30"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability04_Tap"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a7116aa4-2fb7-469b-8d4f-9d402329ec54"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action01_Tap"",
                    ""type"": ""PassThrough"",
                    ""id"": ""22e536a0-f1b7-49c0-91de-b88135e9d98c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action02_Tap"",
                    ""type"": ""PassThrough"",
                    ""id"": ""99f1ae0b-1021-4526-a5b8-ffb56d700281"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action03_Tap"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7cc360fd-3de9-454b-9dc8-8db81c09011b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action04_Tap"",
                    ""type"": ""PassThrough"",
                    ""id"": ""42f23c38-e203-4406-a32c-356acd943312"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Use"",
                    ""type"": ""Button"",
                    ""id"": ""344fe8aa-f207-4375-9e6d-daed1cd85c53"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Button"",
                    ""id"": ""3cb0e9e9-f358-4b5c-9d63-70bb8c3d9a70"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Droid_Shoot"",
                    ""type"": ""PassThrough"",
                    ""id"": ""00e5fe76-9cfb-4e9a-86aa-8c5b608403ae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1f99d960-4a52-4a06-83e7-0d463019f8a9"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Ability01_Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ffe51b85-6b36-44d2-a681-074de770a86a"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Ability01_Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""861cb207-e087-4e9f-a5a7-b4100a81566d"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ability01_Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3e9966f-8060-4777-bec1-b4d521b41e9f"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Ability02_Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d047a5e-cf70-41cd-b257-f05526efe98a"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Ability03_Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f67839d-02a1-4e26-9fe5-f6b49e5ded2a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Ability03_Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ef582ac-4081-412f-ad45-24f988fd2e40"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Ability04_Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd87b637-6439-4422-b061-a7fba9928fc0"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Ability04_Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c7175e9-7eb4-4897-987f-0756b2bc81db"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Action03_Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""497937f5-96a1-45f0-8d9e-830e509e1d21"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Action01_Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9033539-e109-4bc1-a8bf-9dfaab1159b9"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Action01_Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35a75a86-1e04-468b-b3a8-a6d7e44f1fda"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Action02_Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62c46fdd-c28d-4926-a2a3-b292ce260684"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Action04_Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""a7622393-9474-4722-97c3-c0dbf90af8ee"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""56b247ba-dfcc-4604-b390-b460bcb83369"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7f8901ed-5a05-4444-930d-17622094d4f0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""790d8b8a-59b0-411c-92ca-d47889777305"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""75a3c2fc-0f28-4a71-83fe-a73f696f3e33"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c868f5e7-7d4d-4174-b4d6-3e2219a96a29"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e220667-ca2a-4464-a093-0f16a00e2b1e"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone(min=0.5)"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f98cf49-a28a-4e8a-a234-05c4905b4fc8"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42ce013f-92a1-4a6e-a8e8-860f5fad315b"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Action03_Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b1b51d2-f152-41fb-b4fc-723282ca7ea5"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5144f4a-c5b0-46ae-8350-9b6af22a08fc"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12e1d83f-05fd-4a36-8424-624abda32cef"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Droid_Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Mine"",
            ""id"": ""51f97dca-19b9-4cb7-be6c-b08e83392653"",
            ""actions"": [
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""4fe846d7-f6f3-4907-bedb-93b392f95bd8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3a299e99-74df-4abb-8f89-916805285eba"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Debug"",
            ""id"": ""672023f1-bbe0-4316-88c0-b087b3ac3b3c"",
            ""actions"": [
                {
                    ""name"": ""AddResource1"",
                    ""type"": ""Button"",
                    ""id"": ""ebab8bc2-45ce-4850-aa72-02e675c77927"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ResetMine"",
                    ""type"": ""Button"",
                    ""id"": ""85afc0da-6256-4593-a2fa-fa9b70cb5f12"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""97d2ed15-94fc-405d-9e7a-a013411f6aca"",
                    ""path"": ""<Keyboard>/numpadPlus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddResource1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c27b7f0-d0dd-4a94-9475-f41410bc960e"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetMine"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KeyboardMouse"",
            ""bindingGroup"": ""KeyboardMouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // _Game
        m__Game = asset.FindActionMap("_Game", throwIfNotFound: true);
        m__Game_Quitgame = m__Game.FindAction("Quitgame", throwIfNotFound: true);
        m__Game_RestartLevel = m__Game.FindAction("RestartLevel", throwIfNotFound: true);
        m__Game_TogglePostProcessing = m__Game.FindAction("TogglePostProcessing", throwIfNotFound: true);
        m__Game_MusicMute = m__Game.FindAction("MusicMute", throwIfNotFound: true);
        m__Game_ToggleUI = m__Game.FindAction("ToggleUI", throwIfNotFound: true);
        m__Game_Screenshot = m__Game.FindAction("Screenshot", throwIfNotFound: true);
        // _Camera
        m__Camera = asset.FindActionMap("_Camera", throwIfNotFound: true);
        m__Camera_Horizontal = m__Camera.FindAction("Horizontal", throwIfNotFound: true);
        m__Camera_Vertical = m__Camera.FindAction("Vertical", throwIfNotFound: true);
        // _Player
        m__Player = asset.FindActionMap("_Player", throwIfNotFound: true);
        m__Player_Move = m__Player.FindAction("Move", throwIfNotFound: true);
        m__Player_Look = m__Player.FindAction("Look", throwIfNotFound: true);
        m__Player_Ability01_Tap = m__Player.FindAction("Ability01_Tap", throwIfNotFound: true);
        m__Player_Ability02_Tap = m__Player.FindAction("Ability02_Tap", throwIfNotFound: true);
        m__Player_Ability03_Tap = m__Player.FindAction("Ability03_Tap", throwIfNotFound: true);
        m__Player_Ability04_Tap = m__Player.FindAction("Ability04_Tap", throwIfNotFound: true);
        m__Player_Action01_Tap = m__Player.FindAction("Action01_Tap", throwIfNotFound: true);
        m__Player_Action02_Tap = m__Player.FindAction("Action02_Tap", throwIfNotFound: true);
        m__Player_Action03_Tap = m__Player.FindAction("Action03_Tap", throwIfNotFound: true);
        m__Player_Action04_Tap = m__Player.FindAction("Action04_Tap", throwIfNotFound: true);
        m__Player_Use = m__Player.FindAction("Use", throwIfNotFound: true);
        m__Player_Aim = m__Player.FindAction("Aim", throwIfNotFound: true);
        m__Player_Droid_Shoot = m__Player.FindAction("Droid_Shoot", throwIfNotFound: true);
        // Mine
        m_Mine = asset.FindActionMap("Mine", throwIfNotFound: true);
        m_Mine_Select = m_Mine.FindAction("Select", throwIfNotFound: true);
        // Debug
        m_Debug = asset.FindActionMap("Debug", throwIfNotFound: true);
        m_Debug_AddResource1 = m_Debug.FindAction("AddResource1", throwIfNotFound: true);
        m_Debug_ResetMine = m_Debug.FindAction("ResetMine", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // _Game
    private readonly InputActionMap m__Game;
    private I_GameActions m__GameActionsCallbackInterface;
    private readonly InputAction m__Game_Quitgame;
    private readonly InputAction m__Game_RestartLevel;
    private readonly InputAction m__Game_TogglePostProcessing;
    private readonly InputAction m__Game_MusicMute;
    private readonly InputAction m__Game_ToggleUI;
    private readonly InputAction m__Game_Screenshot;
    public struct _GameActions
    {
        private @Controls m_Wrapper;
        public _GameActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Quitgame => m_Wrapper.m__Game_Quitgame;
        public InputAction @RestartLevel => m_Wrapper.m__Game_RestartLevel;
        public InputAction @TogglePostProcessing => m_Wrapper.m__Game_TogglePostProcessing;
        public InputAction @MusicMute => m_Wrapper.m__Game_MusicMute;
        public InputAction @ToggleUI => m_Wrapper.m__Game_ToggleUI;
        public InputAction @Screenshot => m_Wrapper.m__Game_Screenshot;
        public InputActionMap Get() { return m_Wrapper.m__Game; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(_GameActions set) { return set.Get(); }
        public void SetCallbacks(I_GameActions instance)
        {
            if (m_Wrapper.m__GameActionsCallbackInterface != null)
            {
                @Quitgame.started -= m_Wrapper.m__GameActionsCallbackInterface.OnQuitgame;
                @Quitgame.performed -= m_Wrapper.m__GameActionsCallbackInterface.OnQuitgame;
                @Quitgame.canceled -= m_Wrapper.m__GameActionsCallbackInterface.OnQuitgame;
                @RestartLevel.started -= m_Wrapper.m__GameActionsCallbackInterface.OnRestartLevel;
                @RestartLevel.performed -= m_Wrapper.m__GameActionsCallbackInterface.OnRestartLevel;
                @RestartLevel.canceled -= m_Wrapper.m__GameActionsCallbackInterface.OnRestartLevel;
                @TogglePostProcessing.started -= m_Wrapper.m__GameActionsCallbackInterface.OnTogglePostProcessing;
                @TogglePostProcessing.performed -= m_Wrapper.m__GameActionsCallbackInterface.OnTogglePostProcessing;
                @TogglePostProcessing.canceled -= m_Wrapper.m__GameActionsCallbackInterface.OnTogglePostProcessing;
                @MusicMute.started -= m_Wrapper.m__GameActionsCallbackInterface.OnMusicMute;
                @MusicMute.performed -= m_Wrapper.m__GameActionsCallbackInterface.OnMusicMute;
                @MusicMute.canceled -= m_Wrapper.m__GameActionsCallbackInterface.OnMusicMute;
                @ToggleUI.started -= m_Wrapper.m__GameActionsCallbackInterface.OnToggleUI;
                @ToggleUI.performed -= m_Wrapper.m__GameActionsCallbackInterface.OnToggleUI;
                @ToggleUI.canceled -= m_Wrapper.m__GameActionsCallbackInterface.OnToggleUI;
                @Screenshot.started -= m_Wrapper.m__GameActionsCallbackInterface.OnScreenshot;
                @Screenshot.performed -= m_Wrapper.m__GameActionsCallbackInterface.OnScreenshot;
                @Screenshot.canceled -= m_Wrapper.m__GameActionsCallbackInterface.OnScreenshot;
            }
            m_Wrapper.m__GameActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Quitgame.started += instance.OnQuitgame;
                @Quitgame.performed += instance.OnQuitgame;
                @Quitgame.canceled += instance.OnQuitgame;
                @RestartLevel.started += instance.OnRestartLevel;
                @RestartLevel.performed += instance.OnRestartLevel;
                @RestartLevel.canceled += instance.OnRestartLevel;
                @TogglePostProcessing.started += instance.OnTogglePostProcessing;
                @TogglePostProcessing.performed += instance.OnTogglePostProcessing;
                @TogglePostProcessing.canceled += instance.OnTogglePostProcessing;
                @MusicMute.started += instance.OnMusicMute;
                @MusicMute.performed += instance.OnMusicMute;
                @MusicMute.canceled += instance.OnMusicMute;
                @ToggleUI.started += instance.OnToggleUI;
                @ToggleUI.performed += instance.OnToggleUI;
                @ToggleUI.canceled += instance.OnToggleUI;
                @Screenshot.started += instance.OnScreenshot;
                @Screenshot.performed += instance.OnScreenshot;
                @Screenshot.canceled += instance.OnScreenshot;
            }
        }
    }
    public _GameActions @_Game => new _GameActions(this);

    // _Camera
    private readonly InputActionMap m__Camera;
    private I_CameraActions m__CameraActionsCallbackInterface;
    private readonly InputAction m__Camera_Horizontal;
    private readonly InputAction m__Camera_Vertical;
    public struct _CameraActions
    {
        private @Controls m_Wrapper;
        public _CameraActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Horizontal => m_Wrapper.m__Camera_Horizontal;
        public InputAction @Vertical => m_Wrapper.m__Camera_Vertical;
        public InputActionMap Get() { return m_Wrapper.m__Camera; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(_CameraActions set) { return set.Get(); }
        public void SetCallbacks(I_CameraActions instance)
        {
            if (m_Wrapper.m__CameraActionsCallbackInterface != null)
            {
                @Horizontal.started -= m_Wrapper.m__CameraActionsCallbackInterface.OnHorizontal;
                @Horizontal.performed -= m_Wrapper.m__CameraActionsCallbackInterface.OnHorizontal;
                @Horizontal.canceled -= m_Wrapper.m__CameraActionsCallbackInterface.OnHorizontal;
                @Vertical.started -= m_Wrapper.m__CameraActionsCallbackInterface.OnVertical;
                @Vertical.performed -= m_Wrapper.m__CameraActionsCallbackInterface.OnVertical;
                @Vertical.canceled -= m_Wrapper.m__CameraActionsCallbackInterface.OnVertical;
            }
            m_Wrapper.m__CameraActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Horizontal.started += instance.OnHorizontal;
                @Horizontal.performed += instance.OnHorizontal;
                @Horizontal.canceled += instance.OnHorizontal;
                @Vertical.started += instance.OnVertical;
                @Vertical.performed += instance.OnVertical;
                @Vertical.canceled += instance.OnVertical;
            }
        }
    }
    public _CameraActions @_Camera => new _CameraActions(this);

    // _Player
    private readonly InputActionMap m__Player;
    private I_PlayerActions m__PlayerActionsCallbackInterface;
    private readonly InputAction m__Player_Move;
    private readonly InputAction m__Player_Look;
    private readonly InputAction m__Player_Ability01_Tap;
    private readonly InputAction m__Player_Ability02_Tap;
    private readonly InputAction m__Player_Ability03_Tap;
    private readonly InputAction m__Player_Ability04_Tap;
    private readonly InputAction m__Player_Action01_Tap;
    private readonly InputAction m__Player_Action02_Tap;
    private readonly InputAction m__Player_Action03_Tap;
    private readonly InputAction m__Player_Action04_Tap;
    private readonly InputAction m__Player_Use;
    private readonly InputAction m__Player_Aim;
    private readonly InputAction m__Player_Droid_Shoot;
    public struct _PlayerActions
    {
        private @Controls m_Wrapper;
        public _PlayerActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m__Player_Move;
        public InputAction @Look => m_Wrapper.m__Player_Look;
        public InputAction @Ability01_Tap => m_Wrapper.m__Player_Ability01_Tap;
        public InputAction @Ability02_Tap => m_Wrapper.m__Player_Ability02_Tap;
        public InputAction @Ability03_Tap => m_Wrapper.m__Player_Ability03_Tap;
        public InputAction @Ability04_Tap => m_Wrapper.m__Player_Ability04_Tap;
        public InputAction @Action01_Tap => m_Wrapper.m__Player_Action01_Tap;
        public InputAction @Action02_Tap => m_Wrapper.m__Player_Action02_Tap;
        public InputAction @Action03_Tap => m_Wrapper.m__Player_Action03_Tap;
        public InputAction @Action04_Tap => m_Wrapper.m__Player_Action04_Tap;
        public InputAction @Use => m_Wrapper.m__Player_Use;
        public InputAction @Aim => m_Wrapper.m__Player_Aim;
        public InputAction @Droid_Shoot => m_Wrapper.m__Player_Droid_Shoot;
        public InputActionMap Get() { return m_Wrapper.m__Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(_PlayerActions set) { return set.Get(); }
        public void SetCallbacks(I_PlayerActions instance)
        {
            if (m_Wrapper.m__PlayerActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m__PlayerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m__PlayerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m__PlayerActionsCallbackInterface.OnMove;
                @Look.started -= m_Wrapper.m__PlayerActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m__PlayerActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m__PlayerActionsCallbackInterface.OnLook;
                @Ability01_Tap.started -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAbility01_Tap;
                @Ability01_Tap.performed -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAbility01_Tap;
                @Ability01_Tap.canceled -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAbility01_Tap;
                @Ability02_Tap.started -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAbility02_Tap;
                @Ability02_Tap.performed -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAbility02_Tap;
                @Ability02_Tap.canceled -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAbility02_Tap;
                @Ability03_Tap.started -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAbility03_Tap;
                @Ability03_Tap.performed -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAbility03_Tap;
                @Ability03_Tap.canceled -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAbility03_Tap;
                @Ability04_Tap.started -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAbility04_Tap;
                @Ability04_Tap.performed -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAbility04_Tap;
                @Ability04_Tap.canceled -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAbility04_Tap;
                @Action01_Tap.started -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAction01_Tap;
                @Action01_Tap.performed -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAction01_Tap;
                @Action01_Tap.canceled -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAction01_Tap;
                @Action02_Tap.started -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAction02_Tap;
                @Action02_Tap.performed -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAction02_Tap;
                @Action02_Tap.canceled -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAction02_Tap;
                @Action03_Tap.started -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAction03_Tap;
                @Action03_Tap.performed -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAction03_Tap;
                @Action03_Tap.canceled -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAction03_Tap;
                @Action04_Tap.started -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAction04_Tap;
                @Action04_Tap.performed -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAction04_Tap;
                @Action04_Tap.canceled -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAction04_Tap;
                @Use.started -= m_Wrapper.m__PlayerActionsCallbackInterface.OnUse;
                @Use.performed -= m_Wrapper.m__PlayerActionsCallbackInterface.OnUse;
                @Use.canceled -= m_Wrapper.m__PlayerActionsCallbackInterface.OnUse;
                @Aim.started -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAim;
                @Aim.performed -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAim;
                @Aim.canceled -= m_Wrapper.m__PlayerActionsCallbackInterface.OnAim;
                @Droid_Shoot.started -= m_Wrapper.m__PlayerActionsCallbackInterface.OnDroid_Shoot;
                @Droid_Shoot.performed -= m_Wrapper.m__PlayerActionsCallbackInterface.OnDroid_Shoot;
                @Droid_Shoot.canceled -= m_Wrapper.m__PlayerActionsCallbackInterface.OnDroid_Shoot;
            }
            m_Wrapper.m__PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Ability01_Tap.started += instance.OnAbility01_Tap;
                @Ability01_Tap.performed += instance.OnAbility01_Tap;
                @Ability01_Tap.canceled += instance.OnAbility01_Tap;
                @Ability02_Tap.started += instance.OnAbility02_Tap;
                @Ability02_Tap.performed += instance.OnAbility02_Tap;
                @Ability02_Tap.canceled += instance.OnAbility02_Tap;
                @Ability03_Tap.started += instance.OnAbility03_Tap;
                @Ability03_Tap.performed += instance.OnAbility03_Tap;
                @Ability03_Tap.canceled += instance.OnAbility03_Tap;
                @Ability04_Tap.started += instance.OnAbility04_Tap;
                @Ability04_Tap.performed += instance.OnAbility04_Tap;
                @Ability04_Tap.canceled += instance.OnAbility04_Tap;
                @Action01_Tap.started += instance.OnAction01_Tap;
                @Action01_Tap.performed += instance.OnAction01_Tap;
                @Action01_Tap.canceled += instance.OnAction01_Tap;
                @Action02_Tap.started += instance.OnAction02_Tap;
                @Action02_Tap.performed += instance.OnAction02_Tap;
                @Action02_Tap.canceled += instance.OnAction02_Tap;
                @Action03_Tap.started += instance.OnAction03_Tap;
                @Action03_Tap.performed += instance.OnAction03_Tap;
                @Action03_Tap.canceled += instance.OnAction03_Tap;
                @Action04_Tap.started += instance.OnAction04_Tap;
                @Action04_Tap.performed += instance.OnAction04_Tap;
                @Action04_Tap.canceled += instance.OnAction04_Tap;
                @Use.started += instance.OnUse;
                @Use.performed += instance.OnUse;
                @Use.canceled += instance.OnUse;
                @Aim.started += instance.OnAim;
                @Aim.performed += instance.OnAim;
                @Aim.canceled += instance.OnAim;
                @Droid_Shoot.started += instance.OnDroid_Shoot;
                @Droid_Shoot.performed += instance.OnDroid_Shoot;
                @Droid_Shoot.canceled += instance.OnDroid_Shoot;
            }
        }
    }
    public _PlayerActions @_Player => new _PlayerActions(this);

    // Mine
    private readonly InputActionMap m_Mine;
    private IMineActions m_MineActionsCallbackInterface;
    private readonly InputAction m_Mine_Select;
    public struct MineActions
    {
        private @Controls m_Wrapper;
        public MineActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Select => m_Wrapper.m_Mine_Select;
        public InputActionMap Get() { return m_Wrapper.m_Mine; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MineActions set) { return set.Get(); }
        public void SetCallbacks(IMineActions instance)
        {
            if (m_Wrapper.m_MineActionsCallbackInterface != null)
            {
                @Select.started -= m_Wrapper.m_MineActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_MineActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_MineActionsCallbackInterface.OnSelect;
            }
            m_Wrapper.m_MineActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
            }
        }
    }
    public MineActions @Mine => new MineActions(this);

    // Debug
    private readonly InputActionMap m_Debug;
    private IDebugActions m_DebugActionsCallbackInterface;
    private readonly InputAction m_Debug_AddResource1;
    private readonly InputAction m_Debug_ResetMine;
    public struct DebugActions
    {
        private @Controls m_Wrapper;
        public DebugActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @AddResource1 => m_Wrapper.m_Debug_AddResource1;
        public InputAction @ResetMine => m_Wrapper.m_Debug_ResetMine;
        public InputActionMap Get() { return m_Wrapper.m_Debug; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DebugActions set) { return set.Get(); }
        public void SetCallbacks(IDebugActions instance)
        {
            if (m_Wrapper.m_DebugActionsCallbackInterface != null)
            {
                @AddResource1.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnAddResource1;
                @AddResource1.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnAddResource1;
                @AddResource1.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnAddResource1;
                @ResetMine.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnResetMine;
                @ResetMine.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnResetMine;
                @ResetMine.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnResetMine;
            }
            m_Wrapper.m_DebugActionsCallbackInterface = instance;
            if (instance != null)
            {
                @AddResource1.started += instance.OnAddResource1;
                @AddResource1.performed += instance.OnAddResource1;
                @AddResource1.canceled += instance.OnAddResource1;
                @ResetMine.started += instance.OnResetMine;
                @ResetMine.performed += instance.OnResetMine;
                @ResetMine.canceled += instance.OnResetMine;
            }
        }
    }
    public DebugActions @Debug => new DebugActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("KeyboardMouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface I_GameActions
    {
        void OnQuitgame(InputAction.CallbackContext context);
        void OnRestartLevel(InputAction.CallbackContext context);
        void OnTogglePostProcessing(InputAction.CallbackContext context);
        void OnMusicMute(InputAction.CallbackContext context);
        void OnToggleUI(InputAction.CallbackContext context);
        void OnScreenshot(InputAction.CallbackContext context);
    }
    public interface I_CameraActions
    {
        void OnHorizontal(InputAction.CallbackContext context);
        void OnVertical(InputAction.CallbackContext context);
    }
    public interface I_PlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnAbility01_Tap(InputAction.CallbackContext context);
        void OnAbility02_Tap(InputAction.CallbackContext context);
        void OnAbility03_Tap(InputAction.CallbackContext context);
        void OnAbility04_Tap(InputAction.CallbackContext context);
        void OnAction01_Tap(InputAction.CallbackContext context);
        void OnAction02_Tap(InputAction.CallbackContext context);
        void OnAction03_Tap(InputAction.CallbackContext context);
        void OnAction04_Tap(InputAction.CallbackContext context);
        void OnUse(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
        void OnDroid_Shoot(InputAction.CallbackContext context);
    }
    public interface IMineActions
    {
        void OnSelect(InputAction.CallbackContext context);
    }
    public interface IDebugActions
    {
        void OnAddResource1(InputAction.CallbackContext context);
        void OnResetMine(InputAction.CallbackContext context);
    }
}
